name: HubCommand
main: HubCommand\HubCommand
version: 2#
api: 3.0.0
author: IceCruelStuff, iStrafeNubzHDyt

commands:
    hub:
        description: "Teleports you to hub"
        usage: "/hub"

    lobby:
        description: "Teleports you to lobby"
        usage: "/lobby"
