name: HubCommand
main: HubCommand\HubCommand
version: 1#
api: 3.0.0
author: IceCruelStuff, iStrafeNubzHDyt

commands:
    hub:
        description: "Teleports you to hub"
        usage: "/hub"
        permission: hub.command

    lobby:
        description: "Teleports you to lobby"
        usage: "/lobby"
        permission: lobby.command

permission:
    hub.command:
        default: true
        description: "Hub command"

    lobby.command:
        default: true
        description: "Lobby command"
